import Head from 'next/head'

import SearchBar from "../components/SerachBar/SearchBar";
import Tokens from "../components/Tokens/Tokens";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Current Token Price</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchBar />
      <Tokens />
    </div>
  )
}
