import Head from 'next/head'

import SearchBar from "../components/SerachBar/SearchBar";
import TokensList from "../components/TokensList";

export default function Home({ filteredTokens }) {
  return (
    <div>
      <Head>
        <title>Current Token Price</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchBar />
      <TokensList filteredTokens={filteredTokens} />
    </div>
  )
}

export const getServerSideProps = async () => {
    const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false');

    const filteredTokens = await res.json();

    return {
        props: { filteredTokens }
    }
}
